# Set programs that you use
$terminal = alacritty
$fileManager = dolphin
$menu = wofi --style=$HOME/.config/wofi/catppuccin/src/mocha/style.css
$browser = chromium --ozone-platform=wayland
$volume = wpctl
$notifier = mako

